### PR TITLE
FEAT: Method called check anywhere

### LINKED ISSUE #228: Add code check for if a method is invoked
We have a code check that looks if a method was invoked inside a test. We need another one that looks for method invocations anywhere.

### PR DESCRIPTION
**Pull request by sandemiroren1**
This Pull Request works on issue #228. It adds another `MethodCalledAnywhere.java` class to look for Method invocations in any scope. Tests are added inside `MethodCalledAnywhereTest.java`. 

fixes #228 

Worked on by: @sandemiroren1 and @Zakrok09

### CODE REVIEW

**Review by mauricioaniche — APPROVED** [review]
LGTM, folks! Thanks for your contribution!

We are just missing a line about this new check in the README! Can you do that?

**Comment by sandemiroren1** [comment]
I have updated the README to contain the new line.

**Comment by mauricioaniche** [comment]
Just found one more test, @sandemiroren1 ! And then we are ready to MERGE!

**Comment by Zakrok09** [comment]
> Just found one more test, @sandemiroren1 ! And then we are ready to MERGE!

Hello, sir! @sandemiroren1 added some tests that check if a method is never inside the solution.

**Comment by mauricioaniche** [comment]
Thanks for the contribution !

**Pull request merged**
