### PR TITLE
CHORE: References

### PR DESCRIPTION
**Pull request by sandemiroren1**
In this Pull Request we fix various references to the old URL of the repository and update them to the newer ones. 

Closes Issue #224
Worked on by @sandemiroren1 and @Zakrok09.

### CODE REVIEW

**Comment by sandemiroren1** [comment]
We have changed all cse1110/andy references. There are also some places using the reference cse1110/* while linking to a repository should we also change those?

**Comment by martinmladenov** [comment]
@sandemiroren1 We previously had multiple repositories (for Maven, the docker image, and the assignments), but we merged all of those into this repo. Those should now point to the relevant directory in this repo.

**Comment by Zakrok09** [comment]
This should be all references updated, including to this repo and the `assignments` folder. 
The only file that is not updated is the [assignments_test.yml](https://github.com/SERG-Delft/andy/blob/main/.github/old/assignments_test.yml) located in a folder `old` inside `.github`. I suppose this file wouldn't need this update.

**Review by martinmladenov — APPROVED** [review]
LGTM!

**Pull request merged**
